name: Deploy Frontend

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 사용하는 Node.js 버전

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ping-frontend-actions .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ping-frontend-actions

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ping-frontend-actions

      - name: Run Docker container
        run: |
          docker run -d \
            --rm \
            --name ping-frontend-actions \
            -p 80:80 \
            ${{ secrets.DOCKERHUB_USERNAME }}/ping-frontend-actions